### ISSUE TITLE
Add bundle to index error: specified image is a docker schema v1 manifest, which is not supported

### ISSUE THREAD

**Issue by saberkan** [operator-framework/operator-registry#453]
When trying to add a second bundle to index, the following error is shown. 

**Reproduce**

1. Creating index (all ok)
```
$ export BUNDLE_IMG=quay.io/saberkan/memcached-bundle:1.0.0
$ export VERSION=1.0.0
$ make bundle
$ make bundle-build
$ opm index add --bundles quay.io/saberkan/memcached-bundle:1.0.0 --tag  quay.io/saberkan/operator-registry:1.0.0
INFO[0000] building the index                            bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
....
INFO[0001] [podman build --format docker -f index.Dockerfile202385039 -t quay.io/saberkan/operator-registry:1.0.0 .]  bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"

```

2. Adding bundle (error)
```
$ export BUNDLE_IMG=quay.io/saberkan/memcached-bundle:2.0.0
$ export VERSION=2.0.0
$ make bundle
$ make bundle-build
$ opm index add --bundles quay.io/saberkan/memcached-bundle:2.0.0 --from-index  quay.io/saberkan/operator-registry:1.0.0 --tag quay.io/saberkan/operator-registry:1.0.1
INFO[0000] building the index                            bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
INFO[0000] resolved name: quay.io/saberkan/memcached-bundle:1.0.0 
INFO[0000] fetched                                       digest="sha256:31b9745cd96c81c65bb114a73a299b0341a866c949e841310df3c49e5df61df7"
INFO[0000] fetched                                       digest="sha256:f6a9ae2cfdb99cecd86ddab6efad64aa839025a65807540389d7b335cade70ef"
INFO[0000] fetched                                       digest="sha256:40a81d381419988118e74f53070329237b00f429cec63f5074aba09e2149371d"
INFO[0000] fetched                                       digest="sha256:9bcd7dc326efef5ae15143be7c421fe4932a3deb41167405ec4069e64bac19c2"
INFO[0000] fetched                                       digest="sha256:20b79be49f4e6c587dac5e165fd4c26418f12843237798e19005ff9d17efcdc4"
INFO[0001] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:40a81d381419988118e74f53070329237b00f429cec63f5074aba09e2149371d 2116 [] map[] <nil>} 
INFO[0001] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:20b79be49f4e6c587dac5e165fd4c26418f12843237798e19005ff9d17efcdc4 386 [] map[] <nil>} 
INFO[0001] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:f6a9ae2cfdb99cecd86ddab6efad64aa839025a65807540389d7b335cade70ef 449 [] map[] <nil>} 
INFO[0001] Could not find optional dependencies file     dir=bundle_tmp411187097 file=bundle_tmp411187097/metadata load=annotations
INFO[0001] found csv, loading bundle                     dir=bundle_tmp411187097 file=bundle_tmp411187097/manifests load=bundle
INFO[0001] loading bundle file                           dir=bundle_tmp411187097/manifests file=cache.example.com_memcacheds.yaml load=bundle
INFO[0001] loading bundle file                           dir=bundle_tmp411187097/manifests file=memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml load=bundle
INFO[0001] loading bundle file                           dir=bundle_tmp411187097/manifests file=memcached-operator.clusterserviceversion.yaml load=bundle
INFO[0001] Generating dockerfile                         bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
INFO[0001] writing dockerfile: index.Dockerfile202385039  bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
INFO[0001] running podman build                          bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
INFO[0001] [podman build --format docker -f index.Dockerfile202385039 -t quay.io/saberkan/operator-registry:1.0.0 .]  bundles="[quay.io/saberkan/memcached-bundle:1.0.0]"
[saberkan-redhat.com@bastion memcached-operator]$ opm index add --bundles quay.io/saberkan/memcached-bundle:1.0.0 --tag  quay.io/saberkan/operator-registry:1.0.0^C
[saberkan-redhat.com@bastion memcached-operator]$ opm index add --bundles quay.io/saberkan/memcached-bundle:2.0.0 --from-index  quay.io/saberkan/operator-registry:1.0.0 --tag quay.io/saberkan/operator-registry:1.0.1
INFO[0000] building the index                            bundles="[quay.io/saberkan/memcached-bundle:2.0.0]"
INFO[0000] Pulling previous image quay.io/saberkan/operator-registry:1.0.0 to get metadata  bundles="[quay.io/saberkan/memcached-bundle:2.0.0]"
INFO[0000] resolved name: quay.io/saberkan/operator-registry:1.0.0  bundles="[quay.io/saberkan/memcached-bundle:2.0.0]"
Error: specified image is a docker schema v1 manifest, which is not supported
Usage:
  opm index add [flags]
...

```

**Additional information**
```
$ podman version
Version:            1.4.2-stable3
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
$ docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:            1.4.2-stable3
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
$ opm version
Version: version.Version{OpmVersion:"v1.13.9-4-g0e50c92", GitCommit:"0e50c92", BuildDate:"2020-09-23T18:44:05Z", GoOs:"linux", GoArch:"amd64"}
$ operator-sdk version
operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.13.15 linux/amd64", GOOS: "linux", GOARCH: "amd64"

```

**Comment by kevinrizza** [comment]
Right, it looks like the schema version of your index image isn't compatible with `opm` -- `opm` built the index by shelling out to podman on your environment. Can you update podman on your environment and try again? We don't currently have a version support matrix on the project, but I have found that podman version 1.8+ seem to work well for me when I run this locally.

**Comment by jpkrohling** [comment]
I'm using `podman` latest (2.1.1) from Fedora 32, and I sporadically see this error. A somewhat tragic workaround is to remove the Quay project and it will work again:

```console
BUNDLE_VERSION=0.13.0

$ opm index add --bundles quay.io/jpkroehling/opentelemetry-operator-bundle:${BUNDLE_VERSION} --tag quay.io/jpkroehling/opentelemetry-operator-index:${BUNDLE_VERSION}
INFO[0000] building the index                            bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0000] resolved name: quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0 
ERRO[0000] permissive mode disabled                      bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]" error="[specified image is a docker schema v1 manifest, which is not supported, image \"quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0\": not found]"
Error: [specified image is a docker schema v1 manifest, which is not supported, image "quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0": not found]
Usage:
  opm index add [flags]

Examples:
  # Create an index image from scratch with a single bundle image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus@sha256:a3ee653ffa8a0d2bbb2fabb150a94da6e878b6e9eb07defd40dc884effde11a0 --tag quay.io/operator-framework/monitoring:1.0.0
  
  # Add a single bundle image to an index image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0 --from-index quay.io/operator-framework/monitoring:1.0.0 --tag quay.io/operator-framework/monitoring:1.0.1
  
  # Add multiple bundles to an index and generate a Dockerfile instead of an image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0,quay.io/operator-framework/operator-bundle-prometheus:0.22.2 --generate

Flags:
  -i, --binary-image opm        container image for on-image opm command
  -u, --build-tool string       tool to build container images. One of: [docker, podman]. Defaults to podman. Overrides part of container-tool.
  -b, --bundles strings         comma separated list of bundles to add
  -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [docker, podman]
  -f, --from-index string       previous index to add to
      --generate                if enabled, just creates the dockerfile and saves it to local disk
  -h, --help                    help for add
      --mode string             graph update mode that defines how channel graphs are updated. One of: [replaces, semver, semver-skippatch] (default "replaces")
  -d, --out-dockerfile string   if generating the dockerfile, this flag is used to (optionally) specify a dockerfile name
      --permissive              allow registry load errors
  -p, --pull-tool string        tool to pull container images. One of: [none, docker, podman]. Defaults to none. Overrides part of container-tool.
  -t, --tag string              custom tag for container image being built

Global Flags:
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index

$ ## remove quay.io/jpkroehling/opentelemetry-operator-bundle

$ podman push quay.io/jpkroehling/opentelemetry-operator-bundle:${BUNDLE_VERSION}
$ opm index add --bundles quay.io/jpkroehling/opentelemetry-operator-bundle:${BUNDLE_VERSION} --tag quay.io/jpkroehling/opentelemetry-operator-index:${BUNDLE_VERSION} -c docker
INFO[0000] building the index                            bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0000] running /usr/bin/docker pull quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0  bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0002] running docker create                         bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0002] running docker cp                             bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0002] running docker rm                             bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0003] Could not find optional dependencies file     dir=bundle_tmp599758466 file=bundle_tmp599758466/metadata load=annotations
INFO[0003] found csv, loading bundle                     dir=bundle_tmp599758466 file=bundle_tmp599758466/manifests load=bundle
INFO[0003] loading bundle file                           dir=bundle_tmp599758466/manifests file=opentelemetry-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml load=bundle
INFO[0003] loading bundle file                           dir=bundle_tmp599758466/manifests file=opentelemetry-operator.clusterserviceversion.yaml load=bundle
INFO[0003] loading bundle file                           dir=bundle_tmp599758466/manifests file=opentelemetry.io_opentelemetrycollectors.yaml load=bundle
INFO[0003] Generating dockerfile                         bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0003] writing dockerfile: index.Dockerfile162731728  bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0003] running docker build                          bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
INFO[0003] [docker build -f index.Dockerfile162731728 -t quay.io/jpkroehling/opentelemetry-operator-index:0.13.0 .]  bundles="[quay.io/jpkroehling/opentelemetry-operator-bundle:0.13.0]"
```

To me, this isn't happening 100% of the time, but once it starts happening, it can't recover easily.

**Comment by jmccormick2001** [comment]
same issue for me, also on Fedora 32 with latest opm Version: version.Version{OpmVersion:"v1.15.0", GitCommit:"bf13cb4", BuildDate:"2020-10-27T20:59:33Z", GoOs:"linux", GoArch:"amd64"}
and latest podman
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 14:31:11 2020
OS/Arch:      linux/amd64

**Comment by jmccormick2001** [comment]
an update, to fix this, I ended up creating a new Fedora VM, one that does NOT have docker installed on it, but only podman.  Rebuilding everything on this new VM then lets opm work as intended (e.g. adding a bundle to an existing image).

**Comment by jmccormick2001** [comment]
bummer, I spoke too soon...it works the 1st time I push the image but then fails on subsequent attempts:

INFO[0003] resolved name: quay.io/jemccorm/doo-operator-bundle:v0.0.2 
ERRO[0003] permissive mode disabled                      bundles="[quay.io/jemccorm/doo-operator-bundle:v0.0.2]" error="[specified image is a docker schema v1 manifest, which is not supported, image \"quay.io/jemccorm/doo-operator-bundle:v0.0.2\": not found]"
Error: [specified image is a docker schema v1 manifest, which is not supported, image "quay.io/jemccorm/doo-operator-bundle:v0.0.2": not found]
Usage:

**Comment by jensfr** [comment]
Same here, Fedora 32 same podman version.

**Comment by jmccormick2001** [comment]
an update, more testing shows this all works fine if I use the docker.io repo, so I think this is a bug either in quay.io or something in podman that causes quay.io to act in this way.  I'll see about filing a bug in one of those projects.

**Comment by jmccormick2001** [comment]
https://github.com/containers/buildah/issues/2317

**Comment by jonathanvila** [comment]
Hi , I was having the same error but apparently solved with :
* adding "--container-tool podman" to the opm index command
* renaming file ~/.config/containers/libpod.conf to containers.conf

**Comment by mvalarh** [comment]
I have similar problem and previous comment didn't fix the problem. I found out that it has to do something with compression. Here is what i found.

I am doing following
```
/tmp/operator-test/bin/opm index add --bundles quay.io/openshift-community-operators/cert-utils-operator:v0.0.1,quay.io/openshift-community-operators/cert-utils-operator:v0.0.3,quay.io/openshift-community-operators/cert-utils-operator:v0.1.0,quay.io/openshift-community-operators/cert-utils-operator:v0.1.1,quay.io/openshift-community-operators/cert-utils-operator:v0.2.0,quay.io/openshift-community-operators/cert-utils-operator:v0.2.1,quay.io/openshift-community-operators/cert-utils-operator:v0.2.2,quay.io/openshift-community-operators/cert-utils-operator:v1.0.0,quay.io/openshift-community-operators/cert-utils-operator:v1.0.1 --from-index quay.io/openshift-community-operators/catalog:v4.6_test --tag quay.io/openshift-community-operators/catalog:v4.6_test_out
```

Then i would like to push with `v2s2`  and i get
```
[root@ip-172-31-29-117 playbooks]# podman push --format v2s2 quay.io/openshift-community-operators/catalog:v4.6_test_out
Getting image source signatures
Copying blob bca46678c451 done  
Copying blob 474bb0eb6169 skipped: already exists  
Copying blob 1119ff37d4a9 skipped: already exists  
Copying blob d2876ccd415b skipped: already exists  
Copying blob 8ec0aa95ab22 skipped: already exists  
Copying blob 2131139c08ce skipped: already exists  
Copying config fd43822bcc done  
Writing manifest to image destination
Error: error copying image to the remote destination: Error writing manifest: Error uploading manifest v4.6_test_out to quay.io/openshift-community-operators/catalog: manifest invalid: manifest invalid
```
At this stage i could not found how to prove it that local layers are not compresses. So i try to push it to local dir with `--compress` function . (By the way pushing to docker.io works, so it is compressed on fly). Anyway, i did
```
[root@ip-172-31-29-117 playbooks]# podman push --compress quay.io/openshift-community-operators/catalog:v4.6_test_out dir:/tmp/op-tmp
Getting image source signatures
Copying blob 1119ff37d4a9 done  
Copying blob 8ec0aa95ab22 done  
Copying blob d2876ccd415b done  
Copying blob 2131139c08ce done  
Copying blob 474bb0eb6169 done  
Copying blob bca46678c451 done  
Copying config fd43822bcc done  
Writing manifest to image destination
Storing signatures
```
and then copy via skopeo
```
[root@ip-172-31-29-117 playbooks]# skopeo copy dir:/tmp/op docker://quay.io/openshift-community-operators/catalog:v4.6_test_out
Getting image source signatures
Copying blob 083086456ea5 skipped: already exists  
Copying blob 7ba918d4eec5 skipped: already exists  
Copying blob ae611727eb20 skipped: already exists  
Copying blob 9ec1a094f745 skipped: already exists  
Copying blob cb6260d4bb83 skipped: already exists  
Copying blob cdc9d3d20d7b [--------------------------------------] 0.0b / 0.0b
Copying config 6e956409f0 [--------------------------------------] 0.0b / 3.5KiB
Writing manifest to image destination
Storing signatures
```

**Comment by mvalarh** [comment]
Now we can repeat exercise with `index rm` where i would like to show that `podman push` without `--format v2s2` is making image with v1 on quay. So let's go
```
[root@ip-172-31-29-117 playbooks]# /tmp/operator-test/bin/opm index rm --operators cert-utils-operator --from-index quay.io/openshift-community-operators/catalog:v4.6_test_out --tag quay.io/openshift-community-operators/catalog:v4.6_test_out
INFO[0000] building the index                            operators="[cert-utils-operator]"
INFO[0000] Pulling previous image quay.io/openshift-community-operators/catalog:v4.6_test_out to get metadata  operators="[cert-utils-operator]"
INFO[0000] resolved name: quay.io/openshift-community-operators/catalog:v4.6_test_out  operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:43df26cf30cfe478abfd2e85e3081dd22af0d1845f8e2c54a844355fa1993970" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:6e956409f045f28ec59a023c8d0dd36073fd9e8345c66d92de8bffa3a35a49cd" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:083086456ea59f2d6308d4559d99f5d06e5a5a5135ab00c79d82e6cc8c5e8aa9" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:cdc9d3d20d7bc9c7013653ed0e9009d05f549f6abdf29533717cd2da161baeae" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:ae611727eb20968c9afe5c96afae3693428aa2f4006c66765b9b4cc2f10435fa" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:7ba918d4eec59652309c6923863aabb344bcd3181dd978a3a1ffe7573b504937" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:9ec1a094f7456731e802b9557c050a3f69697b9b1fea482a5cb52d94adb7bce6" operators="[cert-utils-operator]"
INFO[0001] fetched                                       digest="sha256:cb6260d4bb83bec3ccd30210ef263d719869db080b73638616044aecc8ad1e32" operators="[cert-utils-operator]"
WARN[0004] {"created":"2021-02-03T10:47:22.977547632Z","container":"9539e2dd07de029502c5413bb6723c66eec8a773348d2a1ed2f481e32a65dea5","container_config":{"Hostname":"48497ffb2495","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"50051/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["registry","serve","--database","/database/index.db"],"Image":"sha256:748a4394fb690e6b2f1c59977a386eddb19ec392844a22ccbb3dcfaa9e89c1d4","Volumes":{},"WorkingDir":"","Entrypoint":["/bin/opm"],"OnBuild":[],"Labels":{"io.buildah.version":"1.19.2","operators.operatorframework.io.index.database.v1":"/database/index.db"}},"config":{"Hostname":"48497ffb2495","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"50051/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["registry","serve","--database","/database/index.db"],"Image":"sha256:748a4394fb690e6b2f1c59977a386eddb19ec392844a22ccbb3dcfaa9e89c1d4","Volumes":{},"WorkingDir":"","Entrypoint":["/bin/opm"],"OnBuild":[],"Labels":{"io.buildah.version":"1.19.2","operators.operatorframework.io.index.database.v1":"/database/index.db"}},"architecture":"amd64","os":"linux","parent":"sha256:29965a0d53df81fd391bc5c5658b0ad3a253b9c99168c3afd87c10dd7f75a674","rootfs":{"type":"layers","diff_ids":["sha256:1119ff37d4a9531330e3b8487863ee8ae0308337351be9d5f8bb38f80790acd9","sha256:8ec0aa95ab224d3f1dc3b429e49bfc08d6d059471bb9c334516460df310cf334","sha256:d2876ccd415b745ba86e4e283769175889f067b68f9fc589d988a6c675c79982","sha256:2131139c08ce93ab60142d3a9509f9777b62a8ef1465468b451034929e71d0fe","sha256:474bb0eb616902906089282a51baa699373919470c594955cd6763d025b9e400","sha256:b07abb58688af103c53418ead005e070eb986bfb68162fc58e9dd59c0100a481"]},"history":[{"created":"2021-01-28T23:19:38.05371373Z","created_by":"/bin/sh -c #(nop) ADD file:0e2d487cd80773e947c8aae6daad3d565b7bb019a954af2b8bff188681c00d81 in / "},{"created":"2021-01-28T23:19:38.219326874Z","created_by":"/bin/sh -c #(nop)  CMD [\"/bin/sh\"]","empty_layer":true},{"created":"2021-02-01T16:14:00.723945593Z","created_by":"/bin/sh -c apk update \u0026\u0026 apk add ca-certificates"},{"created":"2021-02-01T16:14:01.165110851Z","created_by":"/bin/sh -c #(nop) COPY file:d059a61e5fe70800aab11fbc409c1e5e191b9f484f20f506ef2a6ffca1b10fc6 in /etc/nsswitch.conf "},{"created":"2021-02-01T16:14:02.170745644Z","created_by":"/bin/sh -c #(nop) COPY file:f46f74971d701e65856586ff3e683ae837043fdc4b1fc3063efe5be3b475d64b in /bin/opm "},{"created":"2021-02-01T16:14:03.810491521Z","created_by":"/bin/sh -c #(nop) COPY file:d152b88c7d1e4f825edb1173337c2994c80fce349331e1378947a054943f0c10 in /bin/grpc_health_probe "},{"created":"2021-02-03T07:27:08.076075486Z","created_by":"/bin/sh -c #(nop) LABEL operators.operatorframework.io.index.database.v1=/database/index.db","empty_layer":true},{"created":"2021-02-03T10:47:18.012898051Z","created_by":"/bin/sh -c #(nop) ADD file:7d2831fcb567c8379af56a68e7603759dc8c37397ec1f4adca16ad964eb4dcbf in /database/index.db "},{"created":"2021-02-03T10:47:20.020379301Z","created_by":"/bin/sh -c #(nop) EXPOSE 50051","empty_layer":true},{"created":"2021-02-03T10:47:21.589708178Z","created_by":"/bin/sh -c #(nop) ENTRYPOINT [\"/bin/opm\"]","empty_layer":true},{"created":"2021-02-03T10:47:22.97798187Z","created_by":"/bin/sh -c #(nop) CMD [\"registry\", \"serve\", \"--database\", \"/database/index.db\"]","empty_layer":true}]}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:083086456ea59f2d6308d4559d99f5d06e5a5a5135ab00c79d82e6cc8c5e8aa9 2900305 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:7ba918d4eec59652309c6923863aabb344bcd3181dd978a3a1ffe7573b504937 2272271 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:ae611727eb20968c9afe5c96afae3693428aa2f4006c66765b9b4cc2f10435fa 168 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:9ec1a094f7456731e802b9557c050a3f69697b9b1fea482a5cb52d94adb7bce6 17022740 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:cb6260d4bb83bec3ccd30210ef263d719869db080b73638616044aecc8ad1e32 3927445 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0004] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:cdc9d3d20d7bc9c7013653ed0e9009d05f549f6abdf29533717cd2da161baeae 8928294 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0005] deleting packages                             pkg=cert-utils-operator
INFO[0005] input has been sanitized                      pkg=cert-utils-operator
INFO[0005] packages: [cert-utils-operator]               pkg=cert-utils-operator
INFO[0005] removing stranded bundles ["cert-utils-operator.v0.0.1" "cert-utils-operator.v0.0.3" "cert-utils-operator.v0.1.0" "cert-utils-operator.v0.1.1" "cert-utils-operator.v0.2.0" "cert-utils-operator.v0.2.1" "cert-utils-operator.v0.2.2" "cert-utils-operator.v1.0.0"] 
INFO[0005] Generating dockerfile                         operators="[cert-utils-operator]"
INFO[0005] writing dockerfile: index.Dockerfile267919537  operators="[cert-utils-operator]"
INFO[0005] running podman build                          operators="[cert-utils-operator]"
INFO[0005] [podman build --format docker -f index.Dockerfile267919537 -t quay.io/openshift-community-operators/catalog:v4.6_test_out .]  operators="[cert-utils-operator]"
```
I cannot push via format `v2s2`
```
[root@ip-172-31-29-117 playbooks]# podman push --format v2s2 quay.io/openshift-community-operators/catalog:v4.6_test_out
Getting image source signatures
Copying blob 2131139c08ce skipped: already exists  
Copying blob 1272d8048706 skipped: already exists  
Copying blob 474bb0eb6169 skipped: already exists  
Copying blob 1119ff37d4a9 skipped: already exists  
Copying blob 8ec0aa95ab22 skipped: already exists  
Copying blob d2876ccd415b [--------------------------------------] 0.0b / 0.0b
Copying config eb6b2a3512 [--------------------------------------] 0.0b / 3.5KiB
Writing manifest to image destination
Error: error copying image to the remote destination: Error writing manifest: Error uploading manifest v4.6_test_out to quay.io/openshift-community-operators/catalog: manifest invalid: manifest invalid
```
But i can via default (very strange that i am able to push to quay with v1. it should be disabled)
```
[root@ip-172-31-29-117 playbooks]# podman push quay.io/openshift-community-operators/catalog:v4.6_test_out
Getting image source signatures
Copying blob 1272d8048706 skipped: already exists  
Copying blob 8ec0aa95ab22 skipped: already exists  
Copying blob 474bb0eb6169 skipped: already exists  
Copying blob 2131139c08ce skipped: already exists  
Copying blob d2876ccd415b skipped: already exists  
Copying blob 1119ff37d4a9 [--------------------------------------] 0.0b / 0.0b
Copying config eb6b2a3512 [--------------------------------------] 0.0b / 3.5KiB
Writing manifest to image destination
Writing manifest to image destination
Storing signatures
```
When when we try to remove operator from that index we get error that it is v1. :)
```
[root@ip-172-31-29-117 playbooks]# /tmp/operator-test/bin/opm index rm --operators cert-utils-operator --from-index quay.io/openshift-community-operators/catalog:v4.6_test_out --tag quay.io/openshift-community-operators/catalog:v4.6_test_out
INFO[0000] building the index                            operators="[cert-utils-operator]"
INFO[0000] Pulling previous image quay.io/openshift-community-operators/catalog:v4.6_test_out to get metadata  operators="[cert-utils-operator]"
INFO[0000] resolved name: quay.io/openshift-community-operators/catalog:v4.6_test_out  operators="[cert-utils-operator]"
Error: specified image is a docker schema v1 manifest, which is not supported
Usage:
  opm index rm [flags]

Flags:
  -i, --binary-image opm        container image for on-image opm command
  -u, --build-tool string       tool to build container images. One of: [docker, podman]. Defaults to podman. Overrides part of container-tool.
  -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [none, docker, podman]
  -f, --from-index string       previous index to delete from
      --generate                if enabled, just creates the dockerfile and saves it to local disk
  -h, --help                    help for rm
  -o, --operators strings       comma separated list of operators to delete
  -d, --out-dockerfile string   if generating the dockerfile, this flag is used to (optionally) specify a dockerfile name
      --permissive              allow registry load errors
  -p, --pull-tool string        tool to pull container images. One of: [none, docker, podman]. Defaults to none. Overrides part of container-tool.
  -t, --tag string              custom tag for container image being built

Global Flags:
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index
```
When i do trick with `podman push --compress` then it looks fine
```
[root@ip-172-31-29-117 playbooks]# podman push --compress quay.io/openshift-community-operators/catalog:v4.6_test_out dir:/tmp/op-tmp
Getting image source signatures
Copying blob 1119ff37d4a9 done  
Copying blob 8ec0aa95ab22 done  
Copying blob d2876ccd415b done  
Copying blob 2131139c08ce done  
Copying blob 474bb0eb6169 done  
Copying blob 1272d8048706 done  
Copying config eb6b2a3512 done  
Writing manifest to image destination
Storing signatures
[root@ip-172-31-29-117 playbooks]# skopeo copy dir:/tmp/op docker://quay.io/openshift-community-operators/catalog:v4.6_test_out
Getting image source signatures
Copying blob 083086456ea5 skipped: already exists  
Copying blob 7ba918d4eec5 skipped: already exists  
Copying blob ae611727eb20 skipped: already exists  
Copying blob 9ec1a094f745 skipped: already exists  
Copying blob cb6260d4bb83 skipped: already exists  
Copying blob cdc9d3d20d7b [--------------------------------------] 0.0b / 0.0b
Copying config 6e956409f0 [--------------------------------------] 0.0b / 3.5KiB
Writing manifest to image destination
Storing signatures
```
And `index rm` looks fine (no operator found there)
```
[root@ip-172-31-29-117 playbooks]# /tmp/operator-test/bin/opm index rm --operators cert-utils-operator --from-index quay.io/openshift-community-operators/catalog:v4.6_test_out --tag quay.io/openshift-community-operators/catalog:v4.6_test_out
INFO[0000] building the index                            operators="[cert-utils-operator]"
INFO[0000] Pulling previous image quay.io/openshift-community-operators/catalog:v4.6_test_out to get metadata  operators="[cert-utils-operator]"
INFO[0000] resolved name: quay.io/openshift-community-operators/catalog:v4.6_test_out  operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:5ffe7640c08205c457476f1659c31e2a29a4ddabb93ba720a1c6b6aa3f957949" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:7ba918d4eec59652309c6923863aabb344bcd3181dd978a3a1ffe7573b504937" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:b976d1305d7207980abd858cebbd39bc1ae02fe2002aa272edda8e7a27460e61" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:ae611727eb20968c9afe5c96afae3693428aa2f4006c66765b9b4cc2f10435fa" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:9ec1a094f7456731e802b9557c050a3f69697b9b1fea482a5cb52d94adb7bce6" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:cb6260d4bb83bec3ccd30210ef263d719869db080b73638616044aecc8ad1e32" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:eb6b2a351240a2e8aa1ffafd85727f0e165725353620c8e8eb17e387310babf6" operators="[cert-utils-operator]"
INFO[0000] fetched                                       digest="sha256:083086456ea59f2d6308d4559d99f5d06e5a5a5135ab00c79d82e6cc8c5e8aa9" operators="[cert-utils-operator]"
WARN[0005] {"created":"2021-02-03T11:08:24.963800033Z","container":"219312cd3d4c24fa363acf38e3e08da9fe7d098e25f37062c5393792504663ce","container_config":{"Hostname":"9da5e53bc487","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"50051/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["registry","serve","--database","/database/index.db"],"Image":"sha256:748a4394fb690e6b2f1c59977a386eddb19ec392844a22ccbb3dcfaa9e89c1d4","Volumes":{},"WorkingDir":"","Entrypoint":["/bin/opm"],"OnBuild":[],"Labels":{"io.buildah.version":"1.19.2","operators.operatorframework.io.index.database.v1":"/database/index.db"}},"config":{"Hostname":"9da5e53bc487","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"50051/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["registry","serve","--database","/database/index.db"],"Image":"sha256:748a4394fb690e6b2f1c59977a386eddb19ec392844a22ccbb3dcfaa9e89c1d4","Volumes":{},"WorkingDir":"","Entrypoint":["/bin/opm"],"OnBuild":[],"Labels":{"io.buildah.version":"1.19.2","operators.operatorframework.io.index.database.v1":"/database/index.db"}},"architecture":"amd64","os":"linux","parent":"sha256:d612f72b00ee5d43b22ee9bec036aaaecfc30340bd7d4fca565203db91918771","rootfs":{"type":"layers","diff_ids":["sha256:1119ff37d4a9531330e3b8487863ee8ae0308337351be9d5f8bb38f80790acd9","sha256:8ec0aa95ab224d3f1dc3b429e49bfc08d6d059471bb9c334516460df310cf334","sha256:d2876ccd415b745ba86e4e283769175889f067b68f9fc589d988a6c675c79982","sha256:2131139c08ce93ab60142d3a9509f9777b62a8ef1465468b451034929e71d0fe","sha256:474bb0eb616902906089282a51baa699373919470c594955cd6763d025b9e400","sha256:1272d80487064d7f3ce85674cbcea449ec8e48afdf0cb9ab77acf6dd836b27f1"]},"history":[{"created":"2021-01-28T23:19:38.05371373Z","created_by":"/bin/sh -c #(nop) ADD file:0e2d487cd80773e947c8aae6daad3d565b7bb019a954af2b8bff188681c00d81 in / "},{"created":"2021-01-28T23:19:38.219326874Z","created_by":"/bin/sh -c #(nop)  CMD [\"/bin/sh\"]","empty_layer":true},{"created":"2021-02-01T16:14:00.723945593Z","created_by":"/bin/sh -c apk update \u0026\u0026 apk add ca-certificates"},{"created":"2021-02-01T16:14:01.165110851Z","created_by":"/bin/sh -c #(nop) COPY file:d059a61e5fe70800aab11fbc409c1e5e191b9f484f20f506ef2a6ffca1b10fc6 in /etc/nsswitch.conf "},{"created":"2021-02-01T16:14:02.170745644Z","created_by":"/bin/sh -c #(nop) COPY file:f46f74971d701e65856586ff3e683ae837043fdc4b1fc3063efe5be3b475d64b in /bin/opm "},{"created":"2021-02-01T16:14:03.810491521Z","created_by":"/bin/sh -c #(nop) COPY file:d152b88c7d1e4f825edb1173337c2994c80fce349331e1378947a054943f0c10 in /bin/grpc_health_probe "},{"created":"2021-02-03T07:27:08.076075486Z","created_by":"/bin/sh -c #(nop) LABEL operators.operatorframework.io.index.database.v1=/database/index.db","empty_layer":true},{"created":"2021-02-03T11:08:19.000327237Z","created_by":"/bin/sh -c #(nop) ADD file:ac8a832c04201effd371fbb213978b07b7e7310f5a689322c6a200c2a957216e in /database/index.db "},{"created":"2021-02-03T11:08:21.794472891Z","created_by":"/bin/sh -c #(nop) EXPOSE 50051","empty_layer":true},{"created":"2021-02-03T11:08:23.383803417Z","created_by":"/bin/sh -c #(nop) ENTRYPOINT [\"/bin/opm\"]","empty_layer":true},{"created":"2021-02-03T11:08:24.96424684Z","created_by":"/bin/sh -c #(nop) CMD [\"registry\", \"serve\", \"--database\", \"/database/index.db\"]","empty_layer":true}]}  operators="[cert-utils-operator]"
INFO[0005] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:083086456ea59f2d6308d4559d99f5d06e5a5a5135ab00c79d82e6cc8c5e8aa9 2900305 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0005] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:7ba918d4eec59652309c6923863aabb344bcd3181dd978a3a1ffe7573b504937 2272271 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0005] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:ae611727eb20968c9afe5c96afae3693428aa2f4006c66765b9b4cc2f10435fa 168 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0005] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:9ec1a094f7456731e802b9557c050a3f69697b9b1fea482a5cb52d94adb7bce6 17022740 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0005] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:cb6260d4bb83bec3ccd30210ef263d719869db080b73638616044aecc8ad1e32 3927445 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0006] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:b976d1305d7207980abd858cebbd39bc1ae02fe2002aa272edda8e7a27460e61 8928302 [] map[] <nil>}  operators="[cert-utils-operator]"
INFO[0006] deleting packages                             pkg=cert-utils-operator
INFO[0006] input has been sanitized                      pkg=cert-utils-operator
INFO[0006] packages: [cert-utils-operator]               pkg=cert-utils-operator
INFO[0006] no stranded bundles found                    
INFO[0006] Generating dockerfile                         operators="[cert-utils-operator]"
INFO[0006] writing dockerfile: index.Dockerfile550371292  operators="[cert-utils-operator]"
INFO[0006] running podman build                          operators="[cert-utils-operator]"
INFO[0006] [podman build --format docker -f index.Dockerfile550371292 -t quay.io/openshift-community-operators/catalog:v4.6_test_out .]  operators="[cert-utils-operator]"
```

**Comment by exdx** [comment]
Seems like the problem here is somewhere between buildah and quay -- not related to opm directly (which shells out to container tools installed by the user in its current implementation). Closing for now as it's not clear what actions on the opm side should be versus quay.

**Comment by tonyskapunk** [comment]
fwiw, we have been seeing a similar issue, it turned out to be podman building by default oci images[0]

```man
--format

Control the format for the built image’s manifest and configuration data. 
Recognized formats include oci (OCI image-spec v1.0, the default) and docker (version 2, using schema format 2 for the manifest).

Note: You can also override the default format by setting the BUILDAH_FORMAT environment variable.
export BUILDAH_FORMAT=docker
```
Our workaround was to use `BUILDAH_FORMAT=docker podman build ...`

hth

[0] http://docs.podman.io/en/latest/markdown/podman-build.1.html
